<?php

return [
    'defaults' => [
        'instagram' => [
            'discovery' => 'instagram.discovery.basic',
            'enrichment' => 'instagram.profile.standard',
        ],
        'tiktok' => [
            'discovery' => 'tiktok.discovery.basic',
            'enrichment' => 'tiktok.profile.standard',
        ],
    ],

    'cost_classes' => [
        'discovery_basic' => [
            'type' => 'scrape',
            'bucket' => 'scrape',
            'strategy' => 'results_limit',
            'min_units' => 1,
            'multiplier' => 1,
            'divisor' => 10,
            'min_credit_cost' => 1,
        ],
        'profile_standard' => [
            'type' => 'enrichment',
            'bucket' => 'scrape',
            'strategy' => 'target_count',
            'min_units' => 1,
            'multiplier' => 3,
            'divisor' => 4,
            'min_credit_cost' => 1,
        ],
        'content_deep' => [
            'type' => 'enrichment',
            'bucket' => 'scrape',
            'strategy' => 'target_count',
            'min_units' => 1,
            'multiplier' => 2,
            'divisor' => 1,
            'min_credit_cost' => 2,
        ],
        'comments_deep' => [
            'type' => 'enrichment',
            'bucket' => 'scrape',
            'strategy' => 'target_count',
            'min_units' => 1,
            'multiplier' => 2,
            'divisor' => 1,
            'min_credit_cost' => 2,
        ],
    ],

    'modules' => [
        'instagram.discovery.basic' => [
            'key' => 'instagram.discovery.basic',
            'label' => 'Instagram Discovery',
            'platform' => 'instagram',
            'stage' => 'discovery',
            'depth' => 'basic',
            'cost_class' => 'discovery_basic',
            'actor_key' => 'instagram_discovery',
            'target_sheet' => 'Instagram_Posts_Raw',
            'allowed_plans' => ['free', 'pro', 'enterprise'],
            'default_batch_size' => 20,
            'max_batch_size' => 100,
            'fields' => [
                'handle', 'profileUrl', 'fullName', 'followersCount', 'postsCount', 'bio', 'verified', 'profilePicUrl', 'latestPostUrl',
            ],
            'notes' => 'Fast lead discovery from public Instagram search and content results.',
        ],
        'instagram.profile.standard' => [
            'key' => 'instagram.profile.standard',
            'label' => 'Instagram Profile Enrichment',
            'platform' => 'instagram',
            'stage' => 'enrichment',
            'depth' => 'standard',
            'cost_class' => 'profile_standard',
            'actor_key' => 'instagram_profile',
            'target_sheet' => 'Instagram_Profile_Enriched',
            'allowed_plans' => ['pro', 'enterprise'],
            'default_batch_size' => 15,
            'max_batch_size' => 50,
            'fields' => [
                'fullName', 'bio', 'website', 'followersCount', 'followsCount', 'postsCount', 'verified', 'profilePicUrl', 'latestPosts', 'avgLikes', 'avgComments', 'engagementRateEstimate',
            ],
            'notes' => 'Standard creator enrichment for CRM-ready Instagram profile cards.',
        ],
        'instagram.content.deep' => [
            'key' => 'instagram.content.deep',
            'label' => 'Instagram Deep Content Enrichment',
            'platform' => 'instagram',
            'stage' => 'enrichment',
            'depth' => 'deep',
            'cost_class' => 'content_deep',
            'actor_key' => 'instagram_content_deep',
            'target_sheet' => 'Instagram_Profile_Enriched',
            'allowed_plans' => ['enterprise'],
            'default_batch_size' => 10,
            'max_batch_size' => 25,
            'fields' => [
                'recentPostImages', 'captions', 'hashtags', 'mentions', 'sponsoredHints', 'commentsSample', 'avgLikes', 'avgComments', 'postingFrequency',
            ],
            'notes' => 'Enterprise-only deep pass for content patterns and fit signals.',
        ],
        'tiktok.discovery.basic' => [
            'key' => 'tiktok.discovery.basic',
            'label' => 'TikTok Discovery',
            'platform' => 'tiktok',
            'stage' => 'discovery',
            'depth' => 'basic',
            'cost_class' => 'discovery_basic',
            'actor_key' => 'tiktok_discovery',
            'target_sheet' => 'TikTok_Posts_Raw',
            'allowed_plans' => ['free', 'pro', 'enterprise'],
            'default_batch_size' => 20,
            'max_batch_size' => 100,
            'fields' => [
                'handle', 'profileUrl', 'nickname', 'followersCount', 'videoCount', 'bio', 'avatarUrl', 'latestPostUrl',
            ],
            'notes' => 'Fast lead discovery for public TikTok profiles and posts.',
        ],
        'tiktok.profile.standard' => [
            'key' => 'tiktok.profile.standard',
            'label' => 'TikTok Profile Enrichment',
            'platform' => 'tiktok',
            'stage' => 'enrichment',
            'depth' => 'standard',
            'cost_class' => 'profile_standard',
            'actor_key' => 'tiktok_profile',
            'target_sheet' => 'TikTok_Profile_Enriched',
            'allowed_plans' => ['pro', 'enterprise'],
            'default_batch_size' => 10,
            'max_batch_size' => 40,
            'fields' => [
                'nickname', 'bio', 'bioLink', 'followersCount', 'followingCount', 'likesCount', 'videoCount', 'verified', 'avatarUrl', 'latestPosts', 'avgViews', 'avgLikes', 'avgComments',
            ],
            'notes' => 'Standard creator enrichment for CRM-ready TikTok profiles.',
        ],
        'tiktok.comments.deep' => [
            'key' => 'tiktok.comments.deep',
            'label' => 'TikTok Deep Comments Enrichment',
            'platform' => 'tiktok',
            'stage' => 'enrichment',
            'depth' => 'deep',
            'cost_class' => 'comments_deep',
            'actor_key' => 'tiktok_comments_deep',
            'target_sheet' => 'TikTok_Profile_Enriched',
            'allowed_plans' => ['enterprise'],
            'default_batch_size' => 10,
            'max_batch_size' => 25,
            'fields' => [
                'commentsSample', 'commentLikes', 'replyCount', 'audienceQualityHints', 'sentimentHints',
            ],
            'notes' => 'Enterprise-only audience quality pass using public TikTok comments.',
        ],
    ],
];
